/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2013-04-18 11:24:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Simple Market Place</title>\r\n");
      out.write("<LINK REL=STYLESHEET HREF=\"JSP-Styles.css\"  TYPE=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body BGCOLOR=\"#FDF5E6\">\r\n");
      out.write("<h1></h1>\r\n");
      out.write("<table>\r\n");
      out.write("<tr class=\"COLORED\">\r\n");
      out.write("\t<td>fred</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\t<A HREF=\"SharedCounts2.jsp\">SharedCounts2.jsp</A>, and\r\n");
      out.write("\t<A HREF=\"SharedCounts3.jsp\">SharedCounts3.jsp</A>, \r\n");
      out.write("\t\r\n");
      out.write("\t<TABLE BORDER=5 ALIGN=\"CENTER\">\r\n");
      out.write("  <TR><TH CLASS=\"TITLE\">\r\n");
      out.write("      Shared Access Counts: Page 1</TABLE>\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <CENTER>\r\n");
      out.write("<TABLE BORDER=5>\r\n");
      out.write("  <TR><TH CLASS=\"TITLE\">\r\n");
      out.write("      What's New at JspNews.com</TABLE>\r\n");
      out.write("</CENTER>\r\n");
      out.write("<P>\r\n");
      out.write("\r\n");
      out.write("Here is a summary of our four most recent news stories:\r\n");
      out.write("<OL>\r\n");
      out.write("  <LI>dddd\r\n");
      out.write("  <LI>dddd\r\n");
      out.write("  <LI>dsdfsdsdf\r\n");
      out.write("  <LI>sdfsfsf\r\n");
      out.write("</OL>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<H2>Greetings</H2>\r\n");
      out.write("\r\n");
      out.write("<H1 ALIGN=\"CENTER\">Collecting Three Parameters</H1>\r\n");
      out.write("\r\n");
      out.write("<FORM ACTION=\"/servlet/coreservlets.ThreeParams\">\r\n");
      out.write("  First Parameter:  <INPUT TYPE=\"TEXT\" NAME=\"param1\"><BR>\r\n");
      out.write("  Second Parameter: <INPUT TYPE=\"TEXT\" NAME=\"param2\"><BR>\r\n");
      out.write("  Third Parameter:  <INPUT TYPE=\"TEXT\" NAME=\"param3\"><BR>\r\n");
      out.write("  <CENTER>\r\n");
      out.write("    <INPUT TYPE=\"SUBMIT\">\r\n");
      out.write("  </CENTER>\r\n");
      out.write("</FORM>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<H2 ALIGN=\"CENTER\">A Sample Form Using GET</H2>\r\n");
      out.write("\r\n");
      out.write("  <CENTER>\r\n");
      out.write("  First name:\r\n");
      out.write("  <INPUT TYPE=\"TEXT\" NAME=\"firstName\" VALUE=\"Joe\"><BR>\r\n");
      out.write("  Last name:\r\n");
      out.write("  <INPUT TYPE=\"TEXT\" NAME=\"lastName\" VALUE=\"Hacker\"><P>\r\n");
      out.write("  <INPUT TYPE=\"SUBMIT\"> <!-- Press this button to submit form -->\r\n");
      out.write("  </CENTER>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
